services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha1234
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  chatbot:
    build: chatbot/.
    restart: always
    ports:
      - 3000:80
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:senha1234@mongo:27017

  back:
    build: back/.
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:senha1234@mongo:27017