services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha@1234
      
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    